"from pathlib import Path"  
"import sys"  
"sys.path.insert(0, 'src')"  
"from albumexplore.database.csv_loader import load_csv_data, extract_year"  
"csv_dir = Path('csv')"  
"print('CSV directory exists:', csv_dir.exists())"  
"files = list(csv_dir.glob('*.csv'))"  
"print('CSV files found:', len(files))"  
"for f in files[:3]:"  
"    year = extract_year(f.name)"  
"    print(f'File: {f.name}, Year: {year}')" 
