"""add spatial coordinates to albums

Revision ID: 07c2d02b6935
Revises: 
Create Date: 2025-02-17 20:12:31.335115

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '07c2d02b6935'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('albums',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('artist', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('release_date', sa.DateTime(), nullable=True),
    sa.Column('release_year', sa.Integer(), nullable=True),
    sa.Column('length', sa.String(), nullable=True),
    sa.Column('vocal_style', sa.String(), nullable=True),
    sa.Column('country', sa.String(), nullable=True),
    sa.Column('genre', sa.String(), nullable=True),
    sa.Column('x', sa.Float(), nullable=True),
    sa.Column('y', sa.Float(), nullable=True),
    sa.Column('last_updated', sa.DateTime(), nullable=True),
    sa.Column('raw_tags', sa.String(), nullable=True),
    sa.Column('platforms', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('tags',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('category', sa.String(), nullable=True),
    sa.Column('aliases', sa.String(), nullable=True),
    sa.Column('frequency', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('update_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('entity_type', sa.String(), nullable=False),
    sa.Column('entity_id', sa.String(), nullable=False),
    sa.Column('change_type', sa.String(), nullable=False),
    sa.Column('changes', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('album_tags',
    sa.Column('album_id', sa.String(), nullable=True),
    sa.Column('tag_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], )
    )
    op.create_table('tag_hierarchy',
    sa.Column('parent_id', sa.String(), nullable=True),
    sa.Column('child_id', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['child_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['parent_id'], ['tags.id'], )
    )
    op.create_table('tag_relationships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tag1_id', sa.String(), nullable=True),
    sa.Column('tag2_id', sa.String(), nullable=True),
    sa.Column('relationship_type', sa.String(), nullable=False),
    sa.Column('strength', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['tag1_id'], ['tags.id'], ),
    sa.ForeignKeyConstraint(['tag2_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tag_relationships')
    op.drop_table('tag_hierarchy')
    op.drop_table('album_tags')
    op.drop_table('update_history')
    op.drop_table('tags')
    op.drop_table('albums')
    # ### end Alembic commands ###
