"""add_lastfm_mbid_and_source_tracking

Revision ID: 6e2f5522bc50
Revises: 5c6a2cd73ad0
Create Date: 2025-12-30 22:02:14.239329

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e2f5522bc50'
down_revision: Union[str, None] = '5c6a2cd73ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('raw_data_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_artist_sources_artist_id'), 'artist_sources', ['artist_id'], unique=False)
    op.create_table('album_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('album_id', sa.String(), nullable=False),
    sa.Column('source_name', sa.String(), nullable=False),
    sa.Column('source_id', sa.String(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('last_fetched', sa.DateTime(), nullable=True),
    sa.Column('raw_data_path', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['album_id'], ['albums.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_album_sources_album_id'), 'album_sources', ['album_id'], unique=False)
    op.add_column('albums', sa.Column('mbid', sa.String(length=36), nullable=True))
    op.add_column('albums', sa.Column('lastfm_playcount', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('lastfm_listeners', sa.Integer(), nullable=True))
    op.add_column('albums', sa.Column('lastfm_url', sa.String(), nullable=True))
    op.create_index(op.f('ix_albums_mbid'), 'albums', ['mbid'], unique=False)
    op.add_column('artists', sa.Column('mbid', sa.String(length=36), nullable=True))
    op.add_column('artists', sa.Column('lastfm_url', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('country', sa.String(), nullable=True))
    op.add_column('artists', sa.Column('formation_year', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_artists_mbid'), 'artists', ['mbid'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_artists_mbid'), table_name='artists')
    op.drop_column('artists', 'formation_year')
    op.drop_column('artists', 'country')
    op.drop_column('artists', 'lastfm_url')
    op.drop_column('artists', 'mbid')
    op.drop_index(op.f('ix_albums_mbid'), table_name='albums')
    op.drop_column('albums', 'lastfm_url')
    op.drop_column('albums', 'lastfm_listeners')
    op.drop_column('albums', 'lastfm_playcount')
    op.drop_column('albums', 'mbid')
    op.drop_index(op.f('ix_album_sources_album_id'), table_name='album_sources')
    op.drop_table('album_sources')
    op.drop_index(op.f('ix_artist_sources_artist_id'), table_name='artist_sources')
    op.drop_table('artist_sources')
    # ### end Alembic commands ###
