"""Add pa_artist_name_on_album to Album

Revision ID: 9df9e1156461
Revises: dcd166e5a800
Create Date: 2026-01-26 17:49:25.202934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9df9e1156461'
down_revision: Union[str, None] = 'dcd166e5a800'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('pa_artist_name_on_album', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'pa_artist_name_on_album')
    # ### end Alembic commands ###
