"""Add raw_tags column to Album

Revision ID: d6d0395fa0af
Revises: 9df9e1156461
Create Date: 2026-01-26 18:35:06.538815

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6d0395fa0af'
down_revision: Union[str, None] = '9df9e1156461'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('albums', sa.Column('raw_tags', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('albums', 'raw_tags')
    # ### end Alembic commands ###
