"""Refactor models: remove pa cols, add metadata

Revision ID: dcd166e5a800
Revises: 6e2f5522bc50
Create Date: 2026-01-26 17:20:17.792675

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dcd166e5a800'
down_revision: Union[str, None] = '6e2f5522bc50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('album_sources', sa.Column('meta_data', sa.JSON(), nullable=True))
    op.drop_index('ix_albums_pa_album_id', table_name='albums')
    op.drop_column('albums', 'platforms')
    op.drop_column('albums', 'raw_tags')
    op.drop_column('albums', 'source_html_file')
    op.drop_column('albums', 'pa_lineup_text')
    op.drop_column('albums', 'pa_review_count')
    op.drop_column('albums', 'pa_rating_value')
    op.drop_column('albums', 'pa_rating_count')
    op.drop_column('albums', 'pa_artist_name_on_album')
    op.drop_column('albums', 'pa_album_id')
    op.add_column('artist_sources', sa.Column('meta_data', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('artist_sources', 'meta_data')
    op.add_column('albums', sa.Column('pa_album_id', sa.VARCHAR(), nullable=True))
    op.add_column('albums', sa.Column('pa_artist_name_on_album', sa.VARCHAR(), nullable=True))
    op.add_column('albums', sa.Column('pa_rating_count', sa.INTEGER(), nullable=True))
    op.add_column('albums', sa.Column('pa_rating_value', sa.FLOAT(), nullable=True))
    op.add_column('albums', sa.Column('pa_review_count', sa.INTEGER(), nullable=True))
    op.add_column('albums', sa.Column('pa_lineup_text', sa.TEXT(), nullable=True))
    op.add_column('albums', sa.Column('source_html_file', sa.VARCHAR(), nullable=True))
    op.add_column('albums', sa.Column('raw_tags', sa.VARCHAR(), nullable=True))
    op.add_column('albums', sa.Column('platforms', sa.VARCHAR(), nullable=True))
    op.create_index('ix_albums_pa_album_id', 'albums', ['pa_album_id'], unique=False)
    op.drop_column('album_sources', 'meta_data')
    # ### end Alembic commands ###
